### ISSUE TITLE
Home Page Latest Transaction Component

### ISSUE THREAD

**Issue by radekwojpl2** [m-ossolinski/coderscamp_2021_spa_project_2#26]

**Comment by m-ossolinski** [comment]
Tu na pewno będzie trzeba zrobić osobny task na zaciąganie ostatnich 10-15-20 transakcji zależy w jakiej formie to będzie przedstawione.
Na pewno nie będzie (albo fajnie jakby tak nie było) że będzie to tak samo wyglądało jak na liście transakcji. Nie chcemy też żeby ta lista zawierała action buttony edit/delete.

**Comment by m-ossolinski** [comment]
![chrome_WP0JMgctcL](https://user-images.githubusercontent.com/34520610/152634853-e0477338-e688-40a7-9cfa-a8f1436cdbe9.png)
