### ISSUE TITLE
Navigation Menu Component

### ISSUE THREAD

**Issue by radekwojpl2** [m-ossolinski/coderscamp_2021_spa_project_2#27]

**Comment by m-ossolinski** [comment]
add styles navigation sidebar to improve it's look, we don't have design system but we can go with one of the propositions:

https://dribbble.com/shots/9006490-Money-Management-Budget-Finance-Web-App
https://dribbble.com/shots/16239190-BamBank-Digital-Bank-Dashboard

they are similar but this green is nicer for me ;d

videos about how to prep nice nav bar, but you don't have to follow them
https://www.youtube.com/watch?v=CXa0f4-dWi4&ab_channel=BrianDesign
https://www.youtube.com/watch?v=5R9jFHlG6ik&ab_channel=PedroTech
